### ISSUE TITLE
Ne fonctionne pas car pas de site ID dans le retour des API

### ISSUE THREAD

**Issue by Florent-35** [Mystikal57/Somfy_Home_ALARM_API#1]
Bonjour,
J'ai essayé avec mon Client ID et Client Secret obtenus avec https://api.myfox.me/ mais je n'obtiens pas le site ID
Je n'ai rien dans le retour dans items.

A la main, voici ce que j'obtiens : 
curl https://api.myfox.me:443/v2/client/site/items?access_token=xxxxxxxxx
{"status":"OK","timestamp":1601300025,"payload":{"items":[]}}

Sur le site api.myfox.me, ils signalent que la Somfy Home Alarm n'est pas gérée par les API... pas simple de s'y retrouver. Merci Somfy :-( ...   Je trouve lamentable qu'en 2020, ils fournissent des systèmes sans API documentée et surtout qu'on ne puisse pas choisir de désactiver les notifications pour passer en mode nuit.

Dans le fichier config.ini, vous mentionnez qu'il faut vous demander pour avoir les codes.

Merci de votre aide.

Florent

**Comment by Mystikal57** [comment]
Bonjour, essayez avec ces infos:
client_id = 84eddf48-2b8e-11e5-b2a5-124cfab25595_475buqrf8v8kgwoo4gow08gkkc0ck80488wo44s8o48sg84k40
client_secret = 4dsqfntieu0wckwwo40kw848gw4o0c8k4owc80k4go0cs0k844

**Comment by Florent-35** [comment]
Bonjour, 


Cela ne fonctionne pas et si je fais cela en manuel, voici le retour : 



curl https://api.myfox.me/oauth2/token -d 'grant_type=password&client_id=84eddf48-2b8e-11e5-b2a5-124cfab25595_475buqrf8v8kgwoo4gow08gkkc0ck80488wo44s8o48sg84k40&client_secret=4dsqfntieu0wckwwo40kw848gw4o0c8k4owc80k4go0cs0k844&username=monadresse@domaine.fr&password=monPassword 
' 
{"error":"invalid_grant","error_description":"A personal account can only be used by its owner"} 

A priori, on ne peut pas utiliser ces infos avec un compte qui n'est pas le bon. 


Cordialement, 


Florent 
----- Mail original -----

De: "Mystikal57" <notifications@github.com> 
À: "Mystikal57/Somfy_Home_ALARM_API" <Somfy_Home_ALARM_API@noreply.github.com> 
Cc: "Florent-35" <fjournaux@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 28 Septembre 2020 15:48:38 
Objet: Re: [Mystikal57/Somfy_Home_ALARM_API] Ne fonctionne pas car pas de site ID dans le retour des API (#1) 



Bonjour, essayez avec ces infos: 
client_id = 84eddf48-2b8e-11e5-b2a5-124cfab25595_475buqrf8v8kgwoo4gow08gkkc0ck80488wo44s8o48sg84k40 
client_secret = 4dsqfntieu0wckwwo40kw848gw4o0c8k4owc80k4go0cs0k844

**Comment by Mystikal57** [comment]
Ces infos ne sont pas propre au compte mais à l'application mobile.
cette adresse n'est pas la bonne:  https://api.myfox.me/oauth2/token
l'authentification sso se fait via: https://sso.myfox.io/oauth/oauth/v2/token

**Comment by Florent-35** [comment]
c'est bon, cela fonctionne.
Cela venait bien de mes client_id et client_secret qui ne renvoyaient pas de site_id...
Bizarre.
Merci beaucoup

**Comment by Mystikal57** [comment]
Avec plaisir

Attention, hier j'ai modifié le code de la page paramètres afin qu'il trouve automatiquement l'ID de la sirène
