### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by Q3F1S9B** [Mystikal57/Somfy_Home_ALARM_API#2]
Salut, 
merci pour votre travail, j'aimerais faire quelques tests sur mon raspberry pi et du coup j'ai vu la partie me demander dans le fichier config.ini. Donc me voilà ! Est-ce les mêmes client id et secret que ceux nommé dans l'issue précédente ( de Florent35 ) --> Edit: Ça fonctionne avec eux. 
Sinon, est-il possible de prévoir un retour d'état ? Exemple si qqn déverrouille via son badge ou directement via l'app Somfy L'objectif final est d'utiliser homebridge via le plugin homebridge-securitysystem

Bonne journée !

**Comment by Mystikal57** [comment]
Bonjour essayez avec ces identifiants dans le config.ini
client_id = 84eddf48-2b8e-11e5-b2a5-124cfab25595_475buqrf8v8kgwoo4gow08gkkc0ck80488wo44s8o48sg84k40
client_secret = 4dsqfntieu0wckwwo40kw848gw4o0c8k4owc80k4go0cs0k844

**Comment by Q3F1S9B** [comment]
Merci pour la réponse et la Maj sur State.php, c'est nickel
