### ISSUE TITLE
client_id et client_secret

### ISSUE THREAD

**Issue by cmartinl** [Mystikal57/Somfy_Home_ALARM_API#4]
Bonjour,

Comment est-il possible de récupérer le client client_id et client_secret ?
J'ai essayé sur l'url https://api.myfox.io/api/apps mais celle-ci est en erreur.

Une idée ?

Merci de votre aide,

Charles

**Comment by Mystikal57** [comment]
Bonjour,

Voilà les infos:
client_id = 84eddf48-2b8e-11e5-b2a5-124cfab25595_475buqrf8v8kgwoo4gow08gkkc0ck80488wo44s8o48sg84k40
client_secret = 4dsqfntieu0wckwwo40kw848gw4o0c8k4owc80k4go0cs0k844

Je supprime ce message pour éviter que somfy ne les bloque.

**Comment by Mystikal57** [comment]
Informations envoyées

**Comment by cmartinl** [comment]
Merci !

Le mer. 26 avr. 2023 à 16:17, Mystikal57 ***@***.***> a
écrit :
